### PR TITLE
Add output area phosphor widget and demo

### PR DESCRIPTION
**Pull request by dwillmer**
Had to fix up the jupyter-js-output-area as it had never worked. Will backfill the fixes into the js code in jupyter later, concentrating on phosphor now

### CODE REVIEW

**Comment by blink1073** [comment]
Looks good, had to do the following to get it to run on Python 3:

```diff
diff --git a/examples/jupyter-output-area/server.py b/examples/jupyter-output-area/server.py
index 3bba78f..79518a8 100644
--- a/examples/jupyter-output-area/server.py
+++ b/examples/jupyter-output-area/server.py
@@ -1,11 +1,16 @@
-#!/usr/bin/env python2
-from SimpleHTTPServer import SimpleHTTPRequestHandler
-import BaseHTTPServer
+try:
+    from http.server import SimpleHTTPRequestHandler
+    import http.server as BaseHTTPServer
+except ImportError:
+    from SimpleHTTPServer import SimpleHTTPRequestHandler
+    import BaseHTTPServer
+
```

**Comment by blink1073** [comment]
Also, you are using tabs instead of spaces...

**Comment by dwillmer** [comment]
Ah yea, i wasn't aiming for 2+3 compatibility, just a demo :) will add that in, cheers dude!

**Comment by blink1073** [comment]
And 2 spaces for ts, 4 spaces for Python.

**Comment by blink1073** [comment]
Some of us are living in the present. :wink:

**Comment by dwillmer** [comment]
hah, yea, my bad. i switched to sublime as atom kept slowing down, turns out the defaults there aren't good.  apologies!

**Comment by dwillmer** [comment]
Thanks!

**Pull request merged**
